### ISSUE TITLE
Failed to activate the atom-disapproval package

### ISSUE THREAD

**Issue by sviluppatore** [DVG/atom-disapproval#2]
1. I selected restart and install update from the drop-down menu
2. Upon restarting the error was triggered

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-disapproval](https://github.com/dvg/atom-disapproval) package, v0.2.0
### Stack Trace

Failed to activate the atom-disapproval package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/mckibr/.atom/packages/atom-disapproval/lib/atom-disapproval.coffee:4:32)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:300:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:19)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-backbone, v0.6.1
atom-disapproval, v0.2.0
color-picker, v2.0.13
compare-files, v0.6.2
meteor-api, v2.20.0
minimap, v4.15.0

# Dev
No dev packages
```

**Comment by edvardm** [comment]
confirming report above.
